

export default function Main(){
  return(
    <div className="mt-20 container sm">
        <h1 className="text-4xl font-bold text-indigo-600 font-extrabold text-center mb-20">
        Our AI email writer personalizes in seconds
        </h1>
        <div className="flex justify-center">
          <h3 className="text-2xl text-black text-center mb-20">
          Sky rocket your cold emails with unique personalizations generated by AI
          </h3>
        </div>
        <div className="flex justify-center">
          <button className="py-4 px-14 py-2 px-6 rounded hover:shadow-md btn-blue">Try AI Email Writer Now</button>
        </div>
      </div>
  )
}